still
./node_modules/handlebars/lib/index.js
require.extensions is not supported by webpack. Use a loader instead.

Import trace for requested module:
./node_modules/handlebars/lib/index.js
./node_modules/dotprompt/dist/index.js
./node_modules/@genkit-ai/core/lib/registry.js
./node_modules/genkit/lib/registry.js
./node_modules/genkit/lib/genkit.js
./node_modules/genkit/lib/index.mjs
./src/ai/flows/hs-code-suggestion.ts

 ✓ Compiled successfully
   Skipping validation of types
   Skipping linting
 ✓ Collecting page data
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
FirebaseError: Firebase: Error (auth/invalid-api-key).
    at uS (C:\Users\Usuario\Documents\studio-master\.next\server\app\page.js:56:24831)
    at ub (C:\Users\Usuario\Documents\studio-master\.next\server\app\page.js:56:24880)
    at an.instanceFactory (C:\Users\Usuario\Documents\studio-master\.next\server\app\page.js:56:85290)
    at as.getOrInitializeService (C:\Users\Usuario\Documents\studio-master\.next\server\app\page.js:56:8117)
    at as.initialize (C:\Users\Usuario\Documents\studio-master\.next\server\app\page.js:56:7492)
    at lk (C:\Users\Usuario\Documents\studio-master\.next\server\app\page.js:56:64257)
    at c$ (C:\Users\Usuario\Documents\studio-master\.next\server\app\page.js:56:85928)
    at 47890 (C:\Users\Usuario\Documents\studio-master\.next\server\app\page.js:66:65441)
    at Object.t [as require] (C:\Users\Usuario\Documents\studio-master\.next\server\webpack-runtime.js:1:143)
    at require (C:\Users\Usuario\Documents\studio-master\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:133:10079)
Export encountered an error on /page: /, exiting the build.
 ⨯ Next.js build worker exited with code: 1 and signal: null

C:\Users\Usuario\Documents\studio-master>